#!/bin/sh

###################################################################
#Script Name	: wana                                                                                            
#Description	: analyza zaznamu z weeboveho serveru                                                                                                                                                                     
#Author       	: Radek Svec
#Login          : xsvecr01                                               
#Email         	: xsvecr01@stud.fit.vutbr.cz                                           
###################################################################


POSIXLY_CORRECT=yes

PARAMETER=""
VALUE=""
DAYT_AF=""
DAYT_BE=""
IPADDR=""
URI=""
LSIP="false"
LSHOST="false"
LSURI="false"
HSIP="false"
HSLOAD="false"
LOGFILE=""

while [ "$1" != "" ]; do
    PARAMETER="$1"
    VALUE="$2"
    case $PARAMETER in
        -a)
            if [ ! "$2" ]; then 
                echo "Spatne datum"
                exit
            fi
            DAYT_AF=$VALUE
            shift
        ;;
        -b)
            if [ ! "$2" ]; then 
                echo "Spatne datum"
                exit
            fi
            DAYT_BE=$VALUE
            shift
        ;;
        -ip)
            IPADDR=$VALUE
            shift
        ;;
        -uri)
            URI=$VALUE
            shift
        ;;
        list-ip)
            LSIP="true"
        ;;
        list-hosts)
            LSHOST="true"
        ;;
        list-uri)
            LSURI="true"
        ;;
        hist-ip)
            HSIP="true"
        ;;
        hist-load)
            HSLOAD="true"
        ;;
        *)
            LOGFILE="$*"
            break
        ;;
    esac
    shift
done

#Otevreni log souboru
###################################################################
resultlog=$( for log in $LOGFILE ; do
    case "$log" in
    *.gz | *.tgz ) 
        gunzip -c "$log"
        ;;
    *)
        cat "$log"
        ;;
    esac
    done
)

#Pokud neni zadan zadny log soubor, cte z stdin
###################################################################
if [ -z "$resultlog" ]; then
    resultlog=$(cat)
fi

#Filtr ip
###################################################################
if [ "$IPADDR" ]; then
    pomoc=$(echo "$IPADDR" | grep -Eo "[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}")
    if [ "$pomoc" !=  "$IPADDR" ]; then
        pomoc=$(echo "$IPADDR" | grep -E "[0-9a-fA-F]{0,4}:{1,7}[0-9a-fA-F]{0,4}")
    fi
    if [ "$pomoc" = "" ]; then
        echo "wrong ip"
        exit 1
    fi
    if [ "$pomoc" != "$IPADDR" ]; then
        echo "wrong ip"
        exit 1
    fi

    if [ "$pomoc" != "" ]; then
        resultlog=$(echo "$resultlog" | grep -E "$IPADDR" )
    fi
fi

#Filtr uri
###################################################################
if [ "$URI" ]; then
    resultlog=$(echo "$resultlog" | grep -E "$URI" )
fi

#Filtr daytime after
###################################################################
if [ "$DAYT_AF" ]; then
    DAYT_AF=$(echo "$DAYT_AF" | grep -Eo "[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}")
    if [ "$DAYT_AF" = "" ]; then
        exit 1
    fi

    DAYT_AF=$(date -d"$DAYT_AF" +%s)
    resultlog=$(echo "$resultlog" | while read -r line; do 
        prom=$(echo "$line" | grep -Eo "[0-9]{2}[\/][A-Za-z]{2,3}[\/][0-9]{4}[:][0-9]{2}[:][0-9]{2}[:][0-9]{2}" | sed -e "s/\//-/" | sed -e "s/\//-/" | sed -e "s/:/ /")
        datum=$(date -d"$prom" +%s)
        if [ "$DAYT_AF" -lt "$datum" ]; then
            echo "$line"
        fi   
    done )
fi

#Filtr daytime before
###################################################################
if [ "$DAYT_BE" ]; then
    DAYT_BE=$(echo "$DAYT_BE" | grep -Eo "[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}")
    if [ "$DAYT_BE" = "" ]; then
        exit 1
    fi

    DAYT_BE=$(date -d"$DAYT_BE" +%s)
    resultlog=$(echo "$resultlog" | while read -r line; do 
        prom=$(echo "$line" | grep -Eo "[0-9]{2}[\/][A-Za-z]{2,3}[\/][0-9]{4}[:][0-9]{2}[:][0-9]{2}[:][0-9]{2}" | sed -e "s/\//-/" | sed -e "s/\//-/" | sed -e "s/:/ /")
        datum=$(date -d"$prom" +%s)
        if [ "$DAYT_BE" -gt "$datum" ]; then
            echo "$line"
        fi   
    done )
fi

#Prikaz list ip
###################################################################
if [ "$LSIP" = "true" ]; then
    echo "$resultlog" | awk '{print $1}' | sort | uniq
fi

#Prikaz list uri
###################################################################
if [ "$LSURI" = "true" ]; then
    echo "$resultlog" | awk '{print $7}' | sort | uniq | grep -E "\\/"
fi

#Prikaz list host
###################################################################
if [ "$LSHOST" = "true" ]; then
    echo "$resultlog" | awk '{print $1}' | while read -r addr; do 
        temp=$(host "$addr" | awk '{print $NF}')
        if [ "$temp" != "3(NXDOMAIN)" ]; then
            echo "$temp"
        else
            echo "$addr"
        fi
    done | sort | uniq
fi

#Prikaz hist ip
###################################################################
if [ "$HSIP" = "true" ]; then
    
    tmplog=$(echo "$resultlog" | awk '{print $1}' | sort | uniq -c | sort -nr)
    echo "$tmplog" | while read -r addr; do
        count=$(echo "$addr" | awk '{print $1}')
        i=0  
        hash=$(while [ $i -lt "$count" ]; do
            awk 'BEGIN { printf "#" }'
            i=$((i+1))
        done
        )
        echo "$addr" | awk '{printf $2 " (" $1 "): "}'     
        echo "$hash"        
    done
fi

#Prikaz hist load
###################################################################
if [ "$HSLOAD" = "true" ]; then
    tmplog=$(echo "$resultlog" | grep -Eo "[0-9]{2}[\/][A-Za-z]{2,3}[\/][0-9]{4}[:][0-9]{2}[:][0-9]{2}[:][0-9]{2}")
    tmplog=$(echo "$tmplog" | while read -r addr; do
            pes=$(echo "$addr" | sed -e "s/\//-/" | sed -e "s/\//-/" | sed -e "s/:/ /" | sed -e "s/:[0-9][0-9]//" | sed -e "s/:[0-9][0-9]/:00/")
            datum=$(date -d"$pes" +"%Y-%m-%d %H:%M")
            echo "$datum"
        done | sort -n | uniq -c)
    
    echo "$tmplog" | while read -r addr; do
        count=$(echo "$addr" | awk '{print $1}')
        i=0  
        hash=$(while [ $i -lt "$count" ]; do
            awk 'BEGIN { printf "#" }'
            i=$((i+1))
        done
        )
        echo "$addr" | awk '{printf $2 " " $3 " (" $1 "): "}'       
        echo "$hash"        
    done        
fi

#Prikaz list ip
###################################################################
if [ "$LSIP" = "false" ] && [ "$LSHOST" = "false" ] && [ "$LSURI" = "false" ] && [ "$HSLOAD" = "false" ] && [ "$HSIP" = "false" ]; then
    echo "$resultlog"
fi